### ISSUE TITLE
use of thread.sleep

### ISSUE THREAD

**Issue by cxnky** [DJKoston/GGDiscordBot#102]
https://github.com/DJKoston/GGDiscordBot/blob/master/DiscordBot.Bots/Commands/ModCommands.cs#L38

https://github.com/DJKoston/GGDiscordBot/blob/master/DiscordBot.Bots/Commands/ModCommands.cs#L42

https://github.com/DJKoston/GGDiscordBot/blob/master/DiscordBot.Bots/Commands/ModCommands.cs#L46

it's generally a bad idea to use Thread.Sleep within asynchronous code, should be replaced with 

```cs
await Task.Delay(1000);
```

**Comment by DJKoston** [comment]
Thank you for the feedback, any other suggestions, please make another issue :D
