### ISSUE TITLE
RetroNeon353 Private Command

### ISSUE THREAD

**Issue by Retroneon353** [DJKoston/GGDiscordBot#28]
I was thinking i could have a private command and it would be !command and would throw up a gif of Henry stickman distraction dancing

**Comment by DJKoston** [comment]
I will be able to add the command in, however i won't be able to make it private to just you.

**Comment by Retroneon353** [comment]
Thats fine

**Comment by DJKoston** [comment]
Added to Custom Commands for GG - !henry
