### ISSUE TITLE
Alphabetical streamer list for bot

### ISSUE THREAD

**Issue by AP0CALYPTIC** [DJKoston/GGDiscordBot#39]
Your bot if the best bot that has ever been created. But one thing I think could make it next level is if you made it so in the streamer list they appear in alphabetical order. Love you man, keep up the awesome work! <3

**Comment by DJKoston** [comment]
Commit: https://github.com/DJKoston/GGDiscordBot/commit/cfcde187a6afbcd2a2a0093e9f1b5e4995fda1e0
